- name: Codiga GitHub action
  # You may pin to the exact commit or the version.
  # uses: codiga/github-action@bb1f666a4e021c580d3a49df30ee59b90d7cad55
  uses: codiga/github-action@v1
  with:
    # Token to checkout the repository.
    repo_token: 
    # API Token to access Codiga. Set to none if you use access and secret keys
    codiga_api_token: # default is 
    # Minimum grade. Valid options are EXCELLENT, GOOD, NEUTRAL, WARNING, CRITICAL. Leave blank to ignore.
    min_quality_grade: # default is 
    # Minimum quality score from 0 (worst) to 100 (best)
    min_quality_score: # default is 0
    # Maximum defect rate per line of code (e.g. 0.01 for 1 defect per 100 lines of code). Leave 0 to ignore.
    max_defects_rate: # default is 0
    # Maximum number of complex functions rate (e.g. number of complex functions / number of functions). Leave 0 to ignore.
    max_complex_functions_rate: # default is 0
    # Maximum number of long functions rate (e.g. number of long functions / number of functions). Leave 0 to ignore.
    max_long_functions_rate: # default is 0
    # Project on codiga. Will use the preferences of this analysis. Leave blank and no preferences are used
    project_name: # default is 
    # Timeout before giving up (in case analysis takes too long). Default is 10 minutes
    max_timeout_sec: # default is 600
    # Force the GitHub action to analyze a given ref. Leave to none if you want to analyze branch being pushed (default)
    force_ref: # default is none
